### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by leiradel** [oracle/mobile-persistence#6]
While the license.txt file states that the code is released under the MIT license, the Help Content tab that opens up when JDev restarts after installing the accelerator states that it's released under the GPL.

To add more to the confusion, there's a readme.txt file in Runtime/Application Sources which states that the accelerator is provided as-is, but does not state the users' rights and obligations.

It would be nice to dismiss the confusion and use the same license text in all places, and the use of a permissive license like MIT is crucial for its use by companies since the GPL scares most of them away.

**Comment by brunoborges** [comment]
UPDATE: This project is no longer maintained. AMPA is now part of Oracle MAF 2.3.1 http://www.ateam-oracle.com/migrating-ampa-apps-to-oracle-maf-2-3-1-client-data-model/
