### ISSUE TITLE
AMPA Install Issue

### ISSUE THREAD

**Issue by nikunjoracle** [oracle/mobile-persistence#7]
Hi There,

I am trying to install Oracle A-Team Mobile Persistence Accelerator (Build 12.2.1.0.68) and getting following error.

"Unable to load the application file.Workspace MobilePersistenceAccelerator.jws already migrated to newer version (12.2.1.0.0)."

Jdeveloper Version 12.1.3
MAF extension: 2.2.2
Mac OS Yosemite 10.10.5

Any help is welcome.

thanks

**Comment by stevendavelaar** [comment]
This AMPA release can only be used with MAF 2.3 and JDeveloper 12.2.1, see the release notes:
https://github.com/oracle/mobile-persistence/wiki/Release-Notes-12.2.1.0 <https://github.com/oracle/mobile-persistence/wiki/Release-Notes-12.2.1.0>

Kind regards,
Steven Davelaar.

**Comment by nikunjoracle** [comment]
Thanks Steven for quick response.

Is there a way i can get older version of Oracle A-Team Mobile Persistence Accelerator to work with my existing Jdeveloper (12.1.3) and MAF (2.2.2) version?
Or
Do you recommend upgrading to MAF 2.3 and Jdeveloper 12.2.1?

thanks
Nikunj

**Comment by stevendavelaar** [comment]
Nikunj,

Using the drop down list on GitHub home page, you can select another build than master. You can pick build tagged with 12.1.3.x.x.x, However, the developers guide is written for latest 12.2.1.0.68 production build, and MAF 2.3 has fixes for some UI freeze issue that happened when refreshing the UI through background thread.
So, I would recommend to upgrade to JDev 12.2.1 / MAF 2.3. The only annoying thing is that deployment of MAF 2.3 apps fails pretty randomly (not related to AMAP). Solution is to remove the deploy dir and try again. I have logged bugs for this and MAF dev team is currently working on this.

Steven.

**Comment by nikunjoracle** [comment]
thanks Steven for feedback.

Quick question: As you mentioned MAF 2.3 has some issue currently (not related to AMPA). So I don't think its Production ready as we going to deploy our App in Production in early July. (You provided solution...i haven't played around with MAF 2.3 version)

Any comments?

thanks
Nikunj

**Comment by stevendavelaar** [comment]
Nikunj,

MAF 2.3 is a production release, so it is production ready, and I am using it for a couple of weeks without any issues except for the intermittent deployment failures.
I hope the MAF team will bring out a patch pretty soon to fix the deployment issues.

Steven.

**Comment by nikunjoracle** [comment]
Thanks Steven,

I will upgrade to MAF 2.3 in test environment and play around it along with latest AMPA release.

thanks
Nikunj
