### ISSUE TITLE
Synchronisation with pagination

### ISSUE THREAD

**Issue by minhkte** [oracle/mobile-persistence#8]
Hi Team, 

We are currently facing problem when synchronization huge records from server to client. 
Obviously, all data synched is keeping in the memory so it's synched thread has being killed while synchronizing.
I am looking for a way to separate sync data to patch by patch or page by page. 

Thanks,

**Comment by brunoborges** [comment]
UPDATE: This project is no longer maintained. AMPA is now part of Oracle MAF 2.3.1 http://www.ateam-oracle.com/migrating-ampa-apps-to-oracle-maf-2-3-1-client-data-model/
